### ISSUE TITLE
Depends on unpublished package

### ISSUE THREAD

**Issue by doug-wade** [lukekarrys/random-emoji#2]
random-emoji uses shuffle-array, which has been unpublished from npm (https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.ovptnk4p6) to randomize emoji. I've created a "please republish" issue on shuffle-array: https://github.com/pazguille/shuffle-array/issues/11, but in the meantime, fresh installs of clients of random-emoji are going to be broken.

**Comment by lukekarrys** [comment]
Thanks for the info @doug-wade! I switched to using `lodash.shuffle` for now and published `v1.0.1` with that dependency instead.
